/**
 * Generated Lucide runtime modules are tracked and must match the generator.
 */
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '../..');
const packPath = path.join(root, 'src/agent/vnext/sessionWorkspace/canvasIconPack.js');
const indexPath = path.join(root, 'src/agent/vnext/sessionWorkspace/iconCatalogIndex.js');

assert.equal(fs.existsSync(packPath), true, 'canvasIconPack.js missing — run npm run build:icons');
assert.equal(fs.existsSync(indexPath), true, 'iconCatalogIndex.js missing — run npm run build:icons');
assert.match(fs.readFileSync(packPath, 'utf8'), /Generated by scripts\/build-icon-pack\.mjs/);
assert.match(fs.readFileSync(indexPath, 'utf8'), /Generated by scripts\/build-icon-pack\.mjs/);

const check = spawnSync(process.execPath, ['scripts/build-icon-pack.mjs', '--check'], {
  cwd: root,
  encoding: 'utf8'
});
assert.equal(check.status, 0, check.stderr || check.stdout || 'icon pack --check failed');

const { CANVAS_ICON_IDS, CANVAS_ICON_PACK_MODE } = await import(
  '../../src/agent/vnext/sessionWorkspace/canvasIconPack.js'
);
const { ICON_CATALOG_INDEX } = await import('../../src/agent/vnext/sessionWorkspace/iconCatalogIndex.js');
assert.equal(CANVAS_ICON_PACK_MODE, 'full');
assert.ok(CANVAS_ICON_IDS.length >= 1500, `full lucide set too small: ${CANVAS_ICON_IDS.length}`);
assert.equal(ICON_CATALOG_INDEX.length, CANVAS_ICON_IDS.length);
const wallet = ICON_CATALOG_INDEX.find((row) => row.id === 'wallet');
assert.ok(wallet, 'wallet missing from catalog index');
assert.ok(wallet.aliases.includes('finance'), `wallet aliases missing finance: ${wallet.aliases.join(',')}`);
const utensils = ICON_CATALOG_INDEX.find((row) => row.id === 'utensils');
assert.ok(utensils?.aliases.includes('food'), `utensils aliases missing food: ${utensils?.aliases?.join(',')}`);
const cap = ICON_CATALOG_INDEX.find((row) => row.id === 'graduation-cap');
assert.ok(cap?.aliases.includes('education'), `graduation-cap aliases missing education: ${cap?.aliases?.join(',')}`);

console.log(`test_icon_pack_generated: ok icons=${CANVAS_ICON_IDS.length}`);
